name: Build and push Docker image
on:
  workflow_dispatch:
  pull_request:

jobs:
  build-arm:
    runs-on: blacksmith-16vcpu-ubuntu-2204-arm

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: backstage

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: yarn install
        uses: backstage/actions/yarn-install@b3c1841fd69e1658ac631afafd0fb140a2309024 # v0.6.17
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: create-app
        run: npx @backstage/create-app
        env:
          BACKSTAGE_APP_NAME: example-app
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: yarn build
        run: yarn build:backend
        working-directory: ./example-app

      - name: Build and push ARM
        uses: useblacksmith/build-push-action@v1
        with:
          context: './example-app'
          file: ./example-app/packages/backend/Dockerfile
          platforms: linux/arm64
          tags: |
            test
          labels: |
            org.opencontainers.image.description=Docker image generated from the latest Backstage release; this contains what you would get out of the box by running npx @backstage/create-app and building a Docker image from the generated source. This is meant to ease the process of evaluating Backstage for the first time, but also has the severe limitation that there is no way to install additional plugins relevant to your infrastructure.

  build-x86:
    runs-on: blacksmith-16vcpu-ubuntu-2204

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: backstage

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: yarn install
        uses: backstage/actions/yarn-install@b3c1841fd69e1658ac631afafd0fb140a2309024 # v0.6.17
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: create-app
        run: npx @backstage/create-app
        env:
          BACKSTAGE_APP_NAME: example-app
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: yarn build
        run: yarn build:backend
        working-directory: ./example-app

      - name: Build and push x86
        uses: useblacksmith/build-push-action@v1
        with:
          context: './example-app'
          file: ./example-app/packages/backend/Dockerfile
          platforms: linux/amd64
          tags: |
            test
          labels: |
            org.opencontainers.image.description=Docker image generated from the latest Backstage release; this contains what you would get out of the box by running npx @backstage/create-app and building a Docker image from the generated source. This is meant to ease the process of evaluating Backstage for the first time, but also has the severe limitation that there is no way to install additional plugins relevant to your infrastructure.

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "blacksmithcihello/blacksmith-builder"

      - name: Build and push multi-platform
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          context: './example-app'
          file: ./example-app/packages/backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            test
          labels: |
            org.opencontainers.image.description=Docker image generated from the latest Backstage release; this contains what you would get out of the box by running npx @backstage/create-app and building a Docker image from the generated source. This is meant to ease the process of evaluating Backstage for the first time, but also has the severe limitation that there is no way to install additional plugins relevant to your infrastructure.